### ISSUE TITLE
Problem with Unity login

### ISSUE THREAD

**Issue by Oberhaim** [Web3Auth/web3auth-unity-sdk#11]
Hi there, 
Using Unity Editor on Mac M1 pro, building for Android and iOS.
I can't login using gmail or social links.
- I open the Demo Scene
- Change Web3AuthSample ClientID and redirect_url to match my Web3Auth dashboard
- I generate deeplink redirect
- Select Gmail
- Click Login
- Sign in Gmail
- takes me to my redirect page 
- Go back to app and NOTHING happens ....

I tried on both editor and Android with same result. 
The app doesnt change at all and nothing in the console... 
Please help :( 
Thanks a lot !

**Comment by taictdev** [comment]
I guess there might be an issue with your redirect URL.
Can you show me your code?

**Comment by grvgoel81** [comment]
Pls use latest unity sdk version i.e. 2.1.1.
