### ISSUE TITLE
clientId isn't set in setOptions

### ISSUE THREAD

**Issue by edouardruiz** [Web3Auth/web3auth-unity-sdk#18]
Hello,

I noticed that the `clientId` isn't set in the [`setOptions()` method](https://github.com/Web3Auth/web3auth-unity-sdk/blob/master/Assets/Plugins/Web3AuthSDK/Web3Auth.cs#L71-L85) which makes authentication fail with the message `clientId is required` when we set it programmatically (not in the game object in the Unity editor).

Digging in the repo I noticed that this has already been raised in [this issue](https://github.com/Web3Auth/web3auth-unity-sdk/issues/8) which is already closed without a fix.

![clientId is required](https://user-images.githubusercontent.com/6425333/231722244-66020dfb-e3e7-48d4-8356-7b22482e6cbd.jpeg)

**Comment by chaitanyapotti** [comment]
This is fixed in 1.3.0
