### ISSUE TITLE
Conflict with in-app review google

### ISSUE THREAD

**Issue by JohnyBoy-Games** [Web3Auth/web3auth-unity-sdk#20]
Unable to compile

console details

> Configure project: launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

> Task:unityLibrary:preBuild UP-TO-DATE
> Task:launcher:preBuild UP-TO-DATE
etc...

Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\web3auth\unity\android\BrowserView.java:9: error : package androidx.browser.customtabs does not exist
import androidx.browser.customtabs.CustomTabsIntent;

Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\web3auth\unity\android\BrowserView.java:10: error : package androidx.browser.customtabs does not exist
import androidx.browser.customtabs.CustomTabsService;

Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\web3auth\unity\android\BrowserView.java:39: error : cannot find symbol
customTabIntent.setAction(CustomTabsService.ACTION_CUSTOM_TABS_CONNECTION);

after adding the unipackage in-app review from google
https://developers.google.com/unity/packages?hl=fr#play_in-app_review

Unity 2021.3.24f1

**Comment by grvgoel81** [comment]
Pls use latest unity sdk version i.e. 2.1.1.
