### ISSUE TITLE
[Unity - Android] Slow opening web browser and no callback after complete login

### ISSUE THREAD

**Issue by truongntsotanext** [Web3Auth/web3auth-unity-sdk#31]
Hello, I am implementing login system for unity project with web3Auth unity sdk. I tried to test the login on the editor, everything worked. After pressing login, the browser opened and I logged in with google. After successful login, the browser returned data to the unity editor to execute the onlogin function.
Although sometimes it takes 3-5 seconds for the browser to pop up, it's still acceptable.

I perform apk build and launch the application on android device.
After I clicked login, the time it took for the browser to appear was quite long, >10 seconds. After completing the login on the browser, I do not see a callback from the browser returning data to my application. Although I have set up redirect_url according to the instructions Window > Web3Auth > Deep Link Generator.

Here is my initialization code:
![image](https://github.com/Web3Auth/web3auth-unity-sdk/assets/97577458/9101992e-7905-4797-99ac-80ae55efdcf0)
login code:
![image](https://github.com/Web3Auth/web3auth-unity-sdk/assets/97577458/4e003726-53d6-4eb3-a48e-56130e44aff8)
and handle callback:
![image](https://github.com/Web3Auth/web3auth-unity-sdk/assets/97577458/51691713-9831-474a-9dac-067d4d8eb299)

Is there something wrong with my setup?

**Comment by grvgoel81** [comment]
Pls use latest unity sdk version i.e. 2.1.1.
