### ISSUE TITLE
Can't run on Welgl and Mobile

### ISSUE THREAD

**Issue by hiephn** [Web3Auth/web3auth-unity-sdk#9]
When i run your example project on editor,it's ok.

But when i build to webgl or apk file,it run not ok.

![image](https://user-images.githubusercontent.com/13636272/198191573-c2f10266-cf34-4097-ad37-c535096c71fe.png)

It can not open deeplink in webgl.

Also on mobile,it can not authen by browser,alway error.

Do i need to do more?

And more question : how to get {{SCHEMA}}://{YOUR_APP_PACKAGE_NAME}://auth 

Thanks!

**Comment by mubashar1199** [comment]
I am also facing this problem, have you found any workaround?

**Comment by musab1234** [comment]
Hi @mubashar1199  @hiephn , We have added WebGL support in recent version, please check it out.
